apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nucleus-data
  labels:
    {{- include "nucleus.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.dataSize }}
  storageClassName: {{ .Values.storage.storageClassName }}
