apiVersion: v1
kind: Secret
metadata:
  name: nucleus-passwords
  labels:
    {{- include "nucleus.labels" . | nindent 4 }}
type: Opaque
stringData:
  master-password: {{ .Values.masterPassword | quote }}
  service-password: {{ .Values.servicePassword | quote }}
