apiVersion: apps/v1
kind: Deployment
metadata:
  name: nucleus-api
  labels:
    app: nucleus-api
    {{- include "nucleus.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nucleus-api
  template:
    metadata:
      labels:
        app: nucleus-api
    spec:
      serviceAccountName: nucleus
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: nucleus-api
          image: {{ include "nucleus.image" (dict "root" . "image" .Values.images.api) }}
          envFrom:
            - configMapRef:
                name: nucleus-config
          env:
            - name: OMNI_INSTANCE
              valueFrom:
                configMapKeyRef:
                  name: nucleus-config
                  key: INSTANCE_NAME
            - name: OMNI_MASTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nucleus-passwords
                  key: master-password
            - name: OMNI_AUTH_JWT_PUBKEY
              value: /omni/secrets/jwt_pubkey.pub
            - name: OMNI_LFT_ADDRESS
              value: "http://{{ .Values.serverHost }}/omni/lft"
            - name: OMNI_LFT_THRESHOLD
              value: "1024"
            - name: OMNI_CONTENT_RAM_SZ
              value: "6"
            - name: OMNI_NUCLEUS_CORE_THREADS_COUNT
              value: "4"
            - name: OMNI_LAUNCHER_PROMETHEUS_PORT
              value: "9500"
            - name: OMNI_ENABLE_TEST_USER
              value: "0"
            - name: OMNI_S3_RESOLVER_CACHE
              value: "http://nucleus-resolver-cache:8891"
            - name: OMNI_DEFAULT_S3_PROXY_CACHE
              value: "http://nucleus-resolver-cache:8891"
            - name: OMNI_CRASHENABLEUPLOADING
              value: "0"
            - name: OMNI_CRASHREPORTERENABLED
              value: "0"
            - name: OMNI_ENABLE_MOUNT_RESOLVER_LOGGING
              value: "0"
            - name: OMNI_VERSIONING
              valueFrom:
                configMapKeyRef:
                  name: nucleus-config
                  key: ENABLE_VERSIONING
            - name: OMNI_OO_MODE
              value: "0"
            - name: OMNI_CONTENT_MOUNT_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: nucleus-config
                  key: REFERENCE_CONTENT_MOUNT_ENABLE
            - name: OMNI_S3_MOUNT_PATH
              valueFrom:
                configMapKeyRef:
                  name: nucleus-config
                  key: REFERENCE_CONTENT_MOUNT_TARGET
            - name: OMNI_S3_SECURE
              valueFrom:
                configMapKeyRef:
                  name: nucleus-config
                  key: REFERENCE_CONTENT_SECURE
            - name: OMNI_S3_HOST
              valueFrom:
                configMapKeyRef:
                  name: nucleus-config
                  key: REFERENCE_CONTENT_SOURCE
            - name: OMNI_S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: nucleus-config
                  key: REFERENCE_CONTENT_BUCKET
            - name: OMNI_S3_REGION
              valueFrom:
                configMapKeyRef:
                  name: nucleus-config
                  key: REFERENCE_CONTENT_SOURCE_REGION
            - name: OMNI_CONTENT_MOUNT_BUCKET_USE_CREDENTIALS
              valueFrom:
                configMapKeyRef:
                  name: nucleus-config
                  key: REFERENCE_CONTENT_USE_CREDENTIALS
            - name: OMNI_S3_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: nucleus-config
                  key: REFERENCE_CONTENT_BUCKET_ACCESS_KEY_ID
            - name: OMNI_S3_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: nucleus-config
                  key: REFERENCE_CONTENT_BUCKET_SECRET_ACCESS_KEY
            - name: OMNI_S3_RELAXED_XML_PARSING
              valueFrom:
                configMapKeyRef:
                  name: nucleus-config
                  key: REFERENCE_CONTENT_NON_COMPLIANT_XML_SCHEMA
            - name: OMNI_STRUCTURED_LOGGING
              valueFrom:
                configMapKeyRef:
                  name: nucleus-config
                  key: ENABLE_STRUCTURED_LOGGING
            - name: OMNI_MAX_IN_FLIGHT_REQUESTS
              value: "0"
            - name: OMNI_NUCLEUS_DISCOVERY_HOST
              value: nucleus-discovery
            - name: OMNI_NUCLEUS_DISCOVERY_TOKEN_FILE
              value: /omni/secrets/discovery_token
            - name: OMNI_NUCLEUS_SERVICE_AUTH_DEPLOYMENT_LOOKUP
              value: internal
            - name: OMNI_NUCLEUS_DISCOVERY_SERVICE_DEPLOYMENTS
              value: |
                reg:
                  - name: external
                    transport:
                      type: connlib
                      params:
                        url: ws://{{ .Values.serverHost }}/omni/api
                  - name: internal
                    transport:
                      type: connlib
                      params:
                        url: ws://nucleus-api:{{ .Values.ports.api }}
          resources:
            {{- toYaml .Values.resources.api | nindent 12 }}
          ports:
            - containerPort: 3009
            - containerPort: 3106
            - containerPort: 3006
            - containerPort: 3007
          volumeMounts:
            - name: data
              mountPath: /omni/data
              subPath: data
            - name: data
              mountPath: /omni/log
              subPath: log/api
            - name: data
              mountPath: /omni/scratch-meta-dump
              subPath: scratch/meta-dump
            - name: crypto-secrets
              mountPath: /omni/secrets/jwt_pubkey.pub
              subPath: auth_root_of_trust_pub
              readOnly: true
            - name: crypto-secrets
              mountPath: /omni/secrets/discovery_token
              subPath: svc_reg_token
              readOnly: true
            - name: crypto-secrets
              mountPath: /omni/secrets/lft_salt
              subPath: lft_salt
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nucleus-data
        - name: crypto-secrets
          secret:
            secretName: crypto-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: nucleus-api
  labels:
    app: nucleus-api
    {{- include "nucleus.labels" . | nindent 4 }}
spec:
  selector:
    app: nucleus-api
  ports:
    - name: api
      port: {{ .Values.ports.api }}
      targetPort: 3009
    - name: api-authenticated
      port: {{ .Values.ports.apiAuthenticated }}
      targetPort: 3106
    - name: api-admin
      port: 3006
      targetPort: 3006
    - name: api-lft
      port: 3007
      targetPort: 3007
