apiVersion: apps/v1
kind: Deployment
metadata:
  name: nucleus-auth
  labels:
    app: nucleus-auth
    {{- include "nucleus.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nucleus-auth
  template:
    metadata:
      labels:
        app: nucleus-auth
    spec:
      serviceAccountName: nucleus
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: nucleus-auth
          image: {{ include "nucleus.image" (dict "root" . "image" .Values.images.auth) }}
          env:
            - name: ACCEPT_EULA
              value: "1"
            - name: SERVICE_ACCESS_TOKEN_DURATION
              value: "30"
            - name: SERVICE_REFRESH_TOKEN_DURATION
              value: "10080"
            - name: SERVICE_PRIVATE_KEY
              value: /omni/secrets/SERVICE_PRIVATE_KEY
            - name: SERVICE_PUBLIC_KEY
              value: /omni/secrets/SERVICE_PUBLIC_KEY
            - name: SERVICE_PRIVATE_KEY_LONG_TERM_TOKENS
              value: /omni/secrets/SERVICE_PRIVATE_KEY_LONG_TERM_TOKENS
            - name: SERVICE_PUBLIC_KEY_LONG_TERM_TOKENS
              value: /omni/secrets/SERVICE_PUBLIC_KEY_LONG_TERM_TOKENS
            - name: SERVICE_SALT
              value: /omni/secrets/SERVICE_SALT
            - name: SERVICE_DISCOVERY_URL
              value: ws://nucleus-discovery:3333
            - name: SERVICE_DISCOVERY_TOKEN
              value: /omni/secrets/SERVICE_DISCOVERY_TOKEN
            - name: SERVICE_LOG_LEVEL
              value: DEBUG
            - name: CREDENTIAL_AUTO_REGISTER
              value: "False"
            - name: CREDENTIAL_UI_VISIBLE
              value: "true"
            - name: SERVICE_API_TOKENS_ENABLED
              value: "0"
            - name: SERVICE_STRUCTURED_LOGGING
              value: "0"
            - name: SERVICE_FASTAPI_ENABLED
              value: "1"
            - name: SERVICE_FASTAPI_PORT
              value: "8000"
            - name: SERVICE_FASTAPI_ROOT_PATH
              value: /omni/auth/api
            - name: WS_MAX_HTTP_LINE
              value: "65535"
            - name: USE_SAML_SSO
              value: "0"
            - name: USE_OPENID_SSO
              value: "0"
            - name: USE_SSA
              value: "0"
            - name: PUBLIC_URL
              value: /omni/auth-login/
            - name: OPENID_FLOW
              value: "pkce,device"
            - name: MASTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nucleus-passwords
                  key: master-password
            - name: SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nucleus-passwords
                  key: service-password
            - name: SERVICE_DEPLOYMENTS
              value: |
                reg:
                  - name: external
                    transport:
                      type: sows
                      params:
                        host: {{ .Values.serverHost }}
                        port: 80
                        path: /omni/auth
                    meta:
                      login_url: http://{{ .Values.serverHost }}/omni/auth-login/
                  - name: internal
                    transport:
                      type: sows
                      params:
                        host: nucleus-auth
                        port: {{ .Values.ports.auth }}
            - name: CREDENTIAL_USERS
              value: |
                [
                  {
                    "username": "omniverse",
                    "password": "$(MASTER_PASSWORD)",
                    "profile": { "admin": true }
                  },
                  {
                    "username": "tags_service",
                    "password": "$(SERVICE_PASSWORD)",
                    "profile": { "admin": true, "readonly": true }
                  },
                  {
                    "username": "thumbnails_service",
                    "password": "$(SERVICE_PASSWORD)",
                    "profile": { "admin": true, "readonly": true }
                  },
                  {
                    "username": "search_service",
                    "password": "$(SERVICE_PASSWORD)",
                    "profile": { "admin": true, "readonly": true }
                  }
                ]
          resources:
            {{- toYaml .Values.resources.auth | nindent 12 }}
          ports:
            - containerPort: 3100
            - containerPort: 3180
            - containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /omni/data
              subPath: local-accounts-db
            - name: crypto-secrets
              mountPath: /omni/secrets/SERVICE_PRIVATE_KEY
              subPath: auth_root_of_trust_pri
              readOnly: true
            - name: crypto-secrets
              mountPath: /omni/secrets/SERVICE_PUBLIC_KEY
              subPath: auth_root_of_trust_pub
              readOnly: true
            - name: crypto-secrets
              mountPath: /omni/secrets/SERVICE_PRIVATE_KEY_LONG_TERM_TOKENS
              subPath: auth_root_of_trust_lt_pri
              readOnly: true
            - name: crypto-secrets
              mountPath: /omni/secrets/SERVICE_PUBLIC_KEY_LONG_TERM_TOKENS
              subPath: auth_root_of_trust_lt_pub
              readOnly: true
            - name: crypto-secrets
              mountPath: /omni/secrets/SERVICE_SALT
              subPath: pwd_salt
              readOnly: true
            - name: crypto-secrets
              mountPath: /omni/secrets/SERVICE_DISCOVERY_TOKEN
              subPath: svc_reg_token
              readOnly: true
            - name: saml-meta
              mountPath: /omni/secrets/SAML_SSO_META
              subPath: federation.meta.blank.xml
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nucleus-data
        - name: crypto-secrets
          secret:
            secretName: crypto-secrets
        - name: saml-meta
          configMap:
            name: nucleus-saml
---
apiVersion: v1
kind: Service
metadata:
  name: nucleus-auth
  labels:
    app: nucleus-auth
    {{- include "nucleus.labels" . | nindent 4 }}
spec:
  selector:
    app: nucleus-auth
  ports:
    - name: auth
      port: {{ .Values.ports.auth }}
      targetPort: 3100
    - name: auth-login
      port: {{ .Values.ports.authLoginForm }}
      targetPort: 3180
    - name: auth-api
      port: {{ .Values.ports.authApi }}
      targetPort: 8000
