apiVersion: apps/v1
kind: Deployment
metadata:
  name: nucleus-tagging
  labels:
    app: nucleus-tagging
    {{- include "nucleus.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nucleus-tagging
  template:
    metadata:
      labels:
        app: nucleus-tagging
    spec:
      serviceAccountName: nucleus
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: nucleus-tagging
          image: {{ include "nucleus.image" (dict "root" . "image" .Values.images.tagging) }}
          env:
            - name: ACCEPT_EULA
              value: "1"
            - name: OV_HOST_NAME
              value: ""
            - name: OV_SERVICE_BIND_HOST
              value: 0.0.0.0
            - name: OV_SERVICE_BIND_PORT
              value: "3020"
            - name: OV_INSTANCE_NAME
              value: {{ .Values.instanceName | quote }}
            - name: OV_USERNAME
              value: tags_service
            - name: OV_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nucleus-passwords
                  key: service-password
            - name: OV_MEMORY_LIMIT
              value: "2048"
            - name: OV_MEMORY_RESERVE
              value: "256"
            - name: OV_CPU_LIMIT
              value: "1"
            - name: OV_CPU_RESERVE
              value: "0.25"
            - name: OV_REGENERATE_DB
              value: "0"
            - name: OV_UPDATE_TAG_FORMAT_1_0
              value: "0"
            - name: OV_STACK_PROMETHEUS_PORT
              value: "2000"
            - name: OV_LOGFILE
              value: ""
            - name: OV_LOGGING_LEVEL
              value: INFO
            - name: OV_STORAGE_BACKEND
              value: sqlite_backend
            - name: OV_STORAGE_BACKEND_CONFIG
              value: '{"defrag_interval": 86400, "storage_location": "/omni/data/Tagging.db"}'
            - name: SQLITE_TMPDIR
              value: /omni/temp
            - name: SERVICE_AUTH_PUBLIC_KEY
              value: /omni/secrets/SERVICE_AUTH_PUBLIC_KEY
            - name: SERVICE_STRUCTURED_LOGGING
              value: "0"
            - name: WS_MAX_HTTP_LINE
              value: "20000"
            - name: SERVICE_DISCOVERY_URL
              value: ws://nucleus-discovery:3333
            - name: SERVICE_DEPLOYMENTS_LOOKUP
              value: internal
            - name: OV_SERVICE_DISCOVERY_TOKEN_FILE
              value: /omni/secrets/SERVICE_DISCOVERY_TOKEN
            - name: OV_SERVICE_DEPLOYMENTS
              value: |
                reg:
                  - name: external
                    transport:
                      type: sows
                      params:
                        host: {{ .Values.serverHost }}
                        port: 80
                        path: /omni/tagging
                  - name: internal
                    transport:
                      type: sows
                      params:
                        host: nucleus-tagging
                        port: {{ .Values.ports.tagging }}
          resources:
            {{- toYaml .Values.resources.tagging | nindent 12 }}
          ports:
            - containerPort: 3020
          volumeMounts:
            - name: data
              mountPath: /omni/data
              subPath: tags-db
            - name: data
              mountPath: /omni/log
              subPath: log/tagging
            - name: data
              mountPath: /omni/temp
              subPath: tmp/tagging
            - name: crypto-secrets
              mountPath: /omni/secrets/SERVICE_DISCOVERY_TOKEN
              subPath: svc_reg_token
              readOnly: true
            - name: crypto-secrets
              mountPath: /omni/secrets/SERVICE_AUTH_PUBLIC_KEY
              subPath: auth_root_of_trust_pub
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nucleus-data
        - name: crypto-secrets
          secret:
            secretName: crypto-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: nucleus-tagging
  labels:
    app: nucleus-tagging
    {{- include "nucleus.labels" . | nindent 4 }}
spec:
  selector:
    app: nucleus-tagging
  ports:
    - name: tagging
      port: {{ .Values.ports.tagging }}
      targetPort: 3020
